apiVersion: v1
kind: Pod
metadata:
  name: bird-pod
spec:
  containers:
  - name: bird-pod
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    command:
    - sh
    - -c
    - "sudo chmod 777 /birdvol && cd /birdvol && sudo apt-get install gdal-bin && pip install git+https://github.com/ecoscape-earth/scgt.git@v3 && pip install git+https://github.com/ecoscape-earth/ecoscape-utils.git@v3 && pip install git+https://github.com/ecoscape-earth/ecoscape-layers.git@v3 && pip install git+https://github.com/ecoscape-earth/ecoscape-connectivity.git@v3 && sleep infinity"
    volumeMounts:
    - name: birdvol
      mountPath: /birdvol
    - name: dshm
      mountPath: /dev/shm
    resources:
      limits:
        memory: 32Gi
        cpu: "4"
        nvidia.com/rtxa6000: 1
        ephemeral-storage: 32Gi
      requests:
        memory: 32Gi
        cpu: "4"
        nvidia.com/rtxa6000: 1
        ephemeral-storage: 32Gi
  volumes:
  - name: birdvol
    persistentVolumeClaim:
      claimName: birdpvc
  - name: dshm
    emptyDir:
      medium: Memory

